### ISSUE TITLE
Potential to improve manufacturability

### ISSUE THREAD

**Issue by severon10290** [uw-madison-chem-shops/wisconsin-photoreactor#39]
Currently, the top chamber and vile holder are separate parts. If these parts do not need to be removed individually, they could be combined into one piece printed upside down. This would reduce the part count and potentially reduce the time to print each separately. As each vile size appears to have its own height for the associated chamber, this could also make it easier to use by moving the potential for a chamber that is too small to be selected. 

Alternatively, if the top piece needs to be removable, it could be laser cut from a thicker, potentially clear, sheet. This would most likely reduce the fabrication time; however, it would add some complication to fabrication by adding another machine needed to create the device.

**Comment by untzag** [comment]
> Currently, the top chamber and vile holder are separate parts. If these parts do not need to be removed individually, they could be combined into one piece printed upside down.

Actually I agree. It's not clear to me why those two are separate parts. @plampkin would know.

**Comment by plampkin** [comment]
Excellent question! These parts are separated for 2 major reasons:

1. Easy/fast broken part replacement - The part of our design that receives the most wear and is the most prone to breaking is the vial holder. This is due to the the process of repeatedly inserting and removing vials gradually wearing down the plastic. To extend the life of the overall device, it's better to keep the vial holder separate from the reaction chamber (which receives essentially no wear under standard use). 

2. Compatibility of different reaction vessels - Should someone want to run a reaction in a RBF, or some other non-vial reaction vessel that can't easily be inserted into a combined chamber + vial holder unit, having separate parts simplifies the process of designing compatible parts. Though it might be overly optimistic of me to assume anyone would want to run reactions in anything beside vials.

**Comment by untzag** [comment]
OK, I think @plampkin speaks from experience here. Even though a single piece would be easier to 3D print there are clearly practical reasons to make two.

Furthermore @severon10290 your idea of laser cutting the top panels is great if we need to make 100, but I think at our current scale it's simplest to just keep it all on the 3D printer.

Closing this issue, feel free to reopen if more discussion is warranted.
